### ISSUE TITLE
The font display not clear on macOS

### ISSUE THREAD

**Issue by zhengying** [inkyblackness/imgui-go#5] opened 2018-08-24 10:21 UTC
environment：
MacOS 10.12.6

The font display not clear , but native imgui is no problem please see the screenshots:

imgui-go screenshots:

<img width="522" alt="2018-08-24 6 07 39" src="https://user-images.githubusercontent.com/1042545/44579638-9a12f980-a7c9-11e8-8233-7edc60f3bf36.png">

native cpp imgui screenshots:

<img width="547" alt="2018-08-24 6 08 32" src="https://user-images.githubusercontent.com/1042545/44579866-74d2bb00-a7ca-11e8-9311-54bb76b2eca1.png">

**Comment by dertseha** [comment] 2018-08-25 07:04
Thank you for reporting this! I have to look at my options, I may not be able to directly reproduce the issue.

For now it seems like there's a difference in how HiDPI resolution is handled. I'll look whether and how there is a difference in the demo code.
What is your screen resolution?

**Comment by zhengying** [comment] 2018-08-25 18:01
iMac (Retina 5K, 27-inch, 2017)
I run the demo in my macbook air 2011, resolution 1440 x 900 ,  the font display is clear.
so may be the problem is only exist in HiDPI resolution

**Comment by dertseha** [comment] 2018-08-30 20:10
I went through the demo code again, and they are very similar. The only thing that I moved in the Go implementation of the example was where the scaling factor is calculated.
* ImGui example sets IO.DisplayFramebufferScale in ImGui_ImplGlfwGL3_NewFrame, to be used then for draw_data->ScaleClipRects(io.DisplayFramebufferScale)
* Go example skips IO.DisplayFramebufferScale (since it's (almost) only a storage variable to ImGui) and the example calls drawData.ScaleClipRects() with the values calculated right above.
So, conceptually there's no difference between the two demos that I can see at this point.

You are showing screenshot of 1.53 (native). Perhaps there has been a change between 1.53 and 1.61 that this wrapper uses. At least in the demo code I couldn't find any related change.

Apart from that, there are also issues  such as [1065](https://github.com/ocornut/imgui/issues/1065) and [1786](https://github.com/ocornut/imgui/issues/1786) that describe blurry fonts to be handled (currently) in user code, not ImGui.

I don't have access to a Mac/RetinaDisplay, so I can't test on my own. On my MS Windows machine with 4K screen the window/content is unscaled and I have to do manual scaling, ending up with the results as noted in the above issues. For now there seems to be something else at play. If you (or someone else) could test the following:
* Make a comparison between native 1.61 (with the GLFW OpenGL 3 example) and this Go wrapper - to have a direct comparison
* Tinker around with the demo code and look for changes. Since this wrapper is only that, a wrapper, I don't expect the reason to be within that (except any actual bug in transporting values, of course).

**Comment by zhengying** [comment] 2018-08-30 21:27
this is 1.6.1 version compare:

go-imgui:
<img width="518" alt="2018-08-31 5 18 33" src="https://user-images.githubusercontent.com/1042545/44880024-d2409d80-acdd-11e8-830e-a85602b71434.png">

native imgui：
<img width="514" alt="2018-08-31 5 18 50" src="https://user-images.githubusercontent.com/1042545/44880087-fbf9c480-acdd-11e8-978a-280f617b5c97.png">

I will try to modify some code later.

**Comment by dertseha** [comment] 2018-10-05 09:35
I believe to have found the issue.

Based on #6, I re-visited this issue now and tried to reproduce the non-clear font in the native build - and succeeded.

The issue was most likely the shader code that applied the texture! Because this was the only remaining difference between the Go example and the native examples: Since I wanted to avoid the memory waste of the RGBA texture, I only used the Alpha8 texture. Though, this needed a slightly more change to the shader code than I initially did.

Old shader code:
```
Out_Color = Frag_Color * texture( Texture, Frag_UV.st).r;
```
New shader code:
```
Out_Color = vec4(Frag_Color.rgb, Frag_Color.a * texture( Texture, Frag_UV.st).r);
```

The error was that the factor of the texture was applied to all of RGBA of the desired color. While in fact only the A needs to be multiplied by the factor. RGB need to remain original.
So, the old shader code also modified the color value itself, making it darker.

The fix has been committed to the example code. Please try it out.
This is an issue of the example code, hence you'll have to apply the fix in your own codebases.

**Comment by dertseha** [comment] 2018-10-17 18:07
Received one positive confirmation, no more negative feedback.
Closing issue - thank you all for helping!

**Closed by dertseha** 2018-10-17 18:07 UTC
